[build]
  command = "" # No build step needed; HTML files are ready to serve
  publish = "src" # Serve files directly from src

[functions]
  directory = "netlify/functions" # Deploy Netlify Functions for Supabase

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200